### ISSUE TITLE
What a reason this plugin exists?

### ISSUE THREAD

**Issue by netkgk** [sharpdressedcodes/map_with_google#1]
Why don't you use search engine functionality? It's basically the same, except no `javascript` required, and much easier to implement.

**Comment by sharpdressedcodes** [comment]
Because I find it easier to just right-click an address and search for it - without having to type a single word.

**Comment by netkgk** [comment]
But this works exactly how you describe it: https://addons.mozilla.org/en-us/firefox/addon/context-search/

**Comment by sharpdressedcodes** [comment]
I don't quite understand your point. If you don't like my add-on, don't use it.
