### ISSUE TITLE
Options for other mapping tools

### ISSUE THREAD

**Issue by Gitoffthelawn** [sharpdressedcodes/map_with_google#2]
Nice extension!  How about an option to use other mapping tools?

**Comment by sharpdressedcodes** [comment]
Thanks. What other mapping tools do you have in mind?

**Comment by Gitoffthelawn** [comment]
HERE Maps, MapQuest, Bing Maps, OpenStreetMap

**Comment by rosmcmahon** [comment]
I looked into this for you.

MapQuest looked good at first, I even built in an option for it. However, during testing I realised it did not add any value to this addon. It gave me correct addresses at first, but then stopped coming up with what was being searched and was more concerned with finding you a hotel, or whatever, and omitting the correct search results <- even when it had previously returned the actual address! Deleted that branch instantly.

OpenStreetMap does not work for searching addresses, you can not search for a street number for example. And I got a lot of "No results found" for most street names I put in too. Not worth supporting.

Bing Maps is unusable. More geared for access through the API and incurring fees. Also it's just a bit rubbish. You have no control over what language Bing Maps will display in, regardless if you are logged in or not. This affects your searches also. It automatically switches to whatever it decides is the main language in your current location. A bit too "smart" for their own good.

HERE Maps: fee paying, API based again, ref Bing above.

So no luck with any of those I am afraid!

**Comment by Gitoffthelawn** [comment]
@mcmonkeys1 Thank you so much for looking into them!  I'm surprised by the results... mostly.

I think they all have their strengths and weaknesses.  I haven't had the same experiences as you have, but I've learned that it's not uncommon to have very different experiences with services like these.

Thanks again for looking into them... doing so was very kind and generous of you.

**Comment by rosmcmahon** [comment]
Yeah, I was kinda surprised/disappointed myself. Oh well.
